### ISSUE TITLE
Platform specific shortcuts

### ISSUE THREAD

**Issue by idleberg** [morassman/atom-commander#26]
Are you open to making the shortcuts more platform-specific? For instance, on OS X you would use <kbd>Enter</kbd> to rename a file, <kbd>Cmd</kbd><kbd>↓</kbd> to open it, or <kbd>Shift</kbd><kbd>Cmd</kbd><kbd>N</kbd> to create a folder.

If this is generally accepted, I can submit a PR.

**Comment by morassman** [comment]
I think the 'Atom way', so to speak, would probably be to rather create commands for those and let each user bind their own shortcuts to them. Another option would be to have a checkbox under setting like 'Use platform specific keys' that one can check for a more native experience.

I'll look into what a good way would be to approach this, but you're more than welcome to submit a PR. One thing that's important to me, though, is that such a change doesn't become the default. I use OSX and wouldn't be too happy if my shortcuts are suddenly different after an update. It should preferably be something that one must enable explicitly.

Another motivation for requiring an explicit setting is that I try to let Atom Commander behave similar to others of its kind, which is rather consistent, as apposed to the native file manager.

**Comment by idleberg** [comment]
I only realized I probably came to the wrong conclusion that the package is currently following default Windows shortcuts, but that was entirely based on the <kbd>F2</kbd> key. Since that's not the case, I'm hereby withdrawing my previous suggestion 😅

**Comment by morassman** [comment]
It's still a good suggestion though. I started out with Windows and Total Commander (actually DOS and Norton Commander), so I'm used to it, but for users on other platforms it would be reasonable to expect other shortcuts.

I'll close the issue for now, but I'll ponder on it some more. It would at least be a good idea to create more commands so that people can associate their own shortcuts with it.
