### ISSUE TITLE
Move is not supported yet

### ISSUE THREAD

**Issue by NJseo** [morassman/atom-commander#28]
It seems I cant upload a file

**Comment by morassman** [comment]
From the title I assume you are referring to moving a file when working with a remote file system?

I'm aware of this (hence the warning that pops up).  The issue is that the FTP protocol doesn't support moving a file. The only way to do it is to simulate a move, which would involve:
- Downloading the file from to the local file system
- Uploading the downloaded file to the target folder on the remote file system.
- Delete both the original remote file and the local file.

For small files one probably wouldn't notice how inefficient this is, but definitely for bigger files. It's not a high priority to me at the moment, but I'll keep it on the back log.

**Comment by NJseo** [comment]
Yeah, I don't know if you have an alternative, but it seemed like it worked yesterday, but today the FTP didn't work at all?

**Comment by morassman** [comment]
Hi @NJseo. I assume the original intent of this issue was a feature request for moving files when using FTP?

You say now that the FTP worked one day and the next it wasn't working at all. This is a different issue, so please log a separate bug for it. If possible, add more details about the bug as well. Did it not connect? Were there any pop-ups with error messages? Were there any error logs in the console? Anything that can help me debug it will be helpful.

**Comment by morassman** [comment]
This issue has [already](https://github.com/morassman/atom-commander/issues/17) been logged.
