### ISSUE TITLE
Hide Atom Commander after opening a file

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#32]
When you open a file in Atom Commander the next thing you normally want to do is edit it, but  the Atom Commander window stays visible on top of the editor so you have to hit F10 to get to the editor.  It would be more convenient if the Atom Commander window hid itself   automatically after opening a file.

**Comment by morassman** [comment]
Hi @toonbon 

This can be done. I just want to clarify a few things:

1.) The Atom Commander panel is not "on top" of the editor. It is below it. Even while AC is visible you'll have full access to the editor. Nothing is obscured.
2.) After opening a file the editor automatically gains focus. You can just start typing. This was done intentionally, because as you say, that's normally the next thing one would like to to.

As a principle I try to keep the behaviour the same for the sake of the existing users. What I can do in this case is to add a setting that can be enabled so that the panel automatically hides after a file is opened. This setting will be disabled by default so that existing users won't be affected.

**Comment by toonbon** [comment]
_The Atom Commander panel is not "on top" of the editor. It is below it. Even while AC is visible you'll have full access to the editor. Nothing is obscured._

It _looks_  like the AC window has a higher z-index and F10 toggles a display:none for the AC window. You're right, typing goes into the editor after I open a file, but I can't see what's being typed so the editor really isn't usable. 

But it sounds like a setting that hides the AC window when a file is opened would work for me.  I just want to see the file in the editor after I open it in the AC window.   

Thanks.

**Comment by morassman** [comment]
I added a setting that you can enable for the panel to automatically hide after opening a file.

**Comment by toonbon** [comment]
I haven't found this setting yet.

**Comment by morassman** [comment]
A package's settings can be found under Preferences. Click on `Packages`, search for the package, click on it and its settings will be shown.
