### ISSUE TITLE
Additional Context Functions

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#36]
First, thanks for adding the connection username to the upper right of the panel.  That's perfect!

I'd like to also suggest something that would be a huge improvement, - for me - in usability:  in the right-click context menu for a file/directory offer:

rename
delete
copy to other panel

so we don't have to remember F2, F8, and F5.

Actually, while you're at it, it would be nice to also add the _Create file_, _Create folder_, _Duplicate_ and _Move to other panel_ functions there. Right-click is such a natural operation today.  It's where I always look first for options.

Thanks

**Comment by morassman** [comment]
Hi @toonbon. You're welcome!

If these options are in the context menu as well then they will appear on the screen in two places at the same time: The context menu and at the bottom. Besides, you don't really need to remember what the F-keys do. It's written on the buttons. You can just click on the button the same way you would click on them in the menu, but without first having to open it.

I prefer to keep the UI to a minimum, so I'll rather not add these to the menu as well.

**Comment by toonbon** [comment]
Ok, maybe I'm missing something.  I don't see anything at the "bottom" I can click to do one of these things.  Here's a shot of my screen:
![ac6](https://cloud.githubusercontent.com/assets/4875886/18030000/1a2b22dc-6c5d-11e6-88e0-54dc89957438.jpg)

**Comment by morassman** [comment]
There's suppose to be buttons at the bottom of the panel. There's a screenshot of what it should look like on the package's [page](https://atom.io/packages/atom-commander).

This can either be a bug in Atom Commander or another package can be interfering. Maybe you can help me debug this.

1. What OS are you running and which version of Atom do you have installed?
2. What other packages do you have installed? You can determine this by running the following from the command line:
```
apm list --installed
```

PS. I don't have Windows, so I always need help from the community to help me test on it.

**Comment by toonbon** [comment]
I'm running Windows 7 and Atom 1.9.9.
Here's the atm list:
![ac7](https://cloud.githubusercontent.com/assets/4875886/18030247/04322db6-6c64-11e6-95b6-c1cccddec6b2.jpg)

Remote edit is installed, but disabled.

**Comment by morassman** [comment]
Thanks. I'll see if I can reproduce this behaviour and fix it.

**Comment by toonbon** [comment]
Ok.  Just my 2 cents:  Seeing what it's supposed to look like I have to say that the right-click context menu seems better. Everyone's muscle memory is already trained to right-click first and then select from a column that's right there. To use the buttons I have to scan the whole width of the panel at the bottom to find what I want and then click there. Also, there's apparently a Windows issue getting the buttons to appear at the bottom, while the right-click menu already works fine on Windows. :)

**Comment by morassman** [comment]
:) I won't say _everyone's_ muscle memory is trained to right click. Great care was taken to ensure that Atom Commander can be used with only the keyboard, because many people, especially those used to Vim and Emacs, are used to working that way.

Luckily, Atom is very hackable. Not just for developers, but for users as well. You can add these options yourself by doing the following:

1. Open Atom's `init.coffee` file. In Atom's menu there is an entry called `Init Script...` I don't know where this is on Windows, but it's in one of the menus.
2. Paste the following in it:
```
atom.contextMenu.add {
    '.atom-commander': [
      { label: 'Rename', command: 'atom-commander:rename' },
      { label: 'Add Project', command: 'atom-commander:add-project' },
      { label: 'New File', command: 'atom-commander:new-file' },
      { label: 'Copy', command: 'atom-commander:copy' },
      { label: 'Move', command: 'atom-commander:move' },
      { label: 'New Folder', command: 'atom-commander:new-folder' },
      { label: 'Delete', command: 'atom-commander:delete' }
    ]
}
```

After restarting Atom the new menu items should be there. This way you can add any command you'd like to the context menu.

**Comment by toonbon** [comment]
Excellent!  Thank you.

**Comment by morassman** [comment]
I tested this with Atom 1.10.2 on Windows 10 and the buttons at the bottom displayed properly. I can't imagine that this would be an issue with Windows 7, but anything is possible. I'll try to get access to a Windows 7 PC to test on.

If you haven't done so yet, try upgrading Atom to 1.10.2. It might solve the problem. Choose `Check for Update` under the `Help` menu.

**Comment by morassman** [comment]
Do you still experience the problem with the buttons at the bottom not showing? I've tested on Windows 7 and 10 and it displayed properly on both.

**Comment by toonbon** [comment]
I think the problem there was that I usually run with a 40px taskbar along the bottom of my screen and this hid the buttons.  If I temporarily shut off the taskbar I see the buttons.

**Comment by morassman** [comment]
Atom, by default, has a status bar at the bottom that doesn't overlap with anything above it. What is the 40px taskbar you are referring to? Is this another package that you installed?

**Comment by toonbon** [comment]
Ok, I'll give that a try.  The taskbar is part of Windows 7:

![ac19](https://cloud.githubusercontent.com/assets/4875886/18887321/68541dac-84a8-11e6-8239-ba98c5de403f.jpg)

![ac20](https://cloud.githubusercontent.com/assets/4875886/18887328/6ec1dd28-84a8-11e6-894a-0354947e5918.jpg)

![ac21](https://cloud.githubusercontent.com/assets/4875886/18887334/740242b4-84a8-11e6-8dab-37a25be58c14.jpg)

**Comment by morassman** [comment]
I know what the _Windows_ taskbar is:) It just sounded like you were referring to something in Atom. From your screenshot it doesn't seem to overlap with Atom, because I can see Atom's status bar, which is always at the very bottom of the window.

I noticed from one of your previous screenshots that the Atom Commander panel is very large. I then resized my own panel by dragging the separator all the way to the top. This actually caused the buttons to be pushed off. Is this the case with yours? Did you perhaps resize your panel to its max?

**Comment by toonbon** [comment]
_I know what the Windows taskbar is:)_   Sorry.  I know you develop on Apple so I didn't know what your Windows experience was.

To review, the problem I'm having is that clicking in the Commander window moves the contents of the window vertically a bit so that a double-click misfires because the second click is not over what was clicked the first time.  I put in  the styling your provided to get rid of the buttons at the bottom.  The buttons are gone but the double-click problem is still there. 

However, I think I did get rid of the double-click problem by maximizing the window that commander is in. Previously  the window was slightly smaller than full size and was adjustable by dragging corners.  Maximizing to full size with the middle button at the top right - 

![ac22](https://cloud.githubusercontent.com/assets/4875886/18966770/56fe82c8-8637-11e6-9aaf-594f52904c60.jpg)

gives me a much better experience with Commander.  Everything seems stable in that mode

**Comment by morassman** [comment]
:) Yeah. I actually started out with MS-DOS 5 back in the day and upgraded to Windows 95 when it came out and then worked and Windows all the way up to XP. The Mac is relatively recent.

I'm running Windows on my other Mac and I was finally able to reproduce the issue. I must say though, it's quite a corner case. This only happens when the Atom Commander panel is resized all the way to the top.

Atom Commander is meant to be docked at the bottom of the screen, below the editor, but from your last screenshot I can see that it actually goes all the way to the top of the window.

In the screenshot below you can see the panel docked at the bottom with the editor on top. Like this it works fine.

![image](https://cloud.githubusercontent.com/assets/13697130/18968046/c2088992-8687-11e6-9b4a-fc4a44cc4d3f.png)

In the following screenshot you can see it resized to the top. This is done by dragging the separator all the way up there.

![image](https://cloud.githubusercontent.com/assets/13697130/18968079/e7e6bbd4-8687-11e6-8253-bea7cad6d269.png)

This is when the behaviour you are seeing manifests. You can even see that the buttons are missing. I don't know why it happens, but I'm pretty confident that it only happens in when the panel is like this. Even when the window was maximised I could reproduce it when the list of files got long enough.

If you don't mind me asking, why is your panel resized all the way to the top? If you want a dual pane file manager that takes up the whole window the I can really recommend [Total Commander](https://www.ghisler.com). I always used it when I still worked on Windows.

**Comment by toonbon** [comment]
I wasn't trying to exclude three panes, as you've set up, I just didn't run into the Atom/Commander commands to set it up that way.  I wouldn't mind trying it, though.   I just tried playing with the View | Panes options but nothing created what you have.  I hadn't heard of Total Commander.  I downloaded  it and I'll try it out.
