### ISSUE TITLE
Disappearing Lines

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#38]
I'm running on Windows 7 and am having trouble with the screen jumping around.When I'm in the editor there are four information lines at the bottom of the pane:
![ac11a](https://cloud.githubusercontent.com/assets/4875886/18360207/f02adb72-75b1-11e6-93a8-8a697ea2ec2f.jpg)

 The first three lines are related to the Find/Replace function and the bottom line shows the file currently  loaded into the editor.

When you switch with F10 to the panel mode all four of these lines still appear, but they don't seem to have any purpose on the new page and they interfere with the display: 
![ac12](https://cloud.githubusercontent.com/assets/4875886/18360245/0e39ae68-75b2-11e6-87fd-f01361b9e886.jpg)

The first three lines disappear when you first click in the panel screen, jerking the entire display suddenly up about an inch.  If you’re trying to double-click a folder to open it, the first click is on the folder and the second click, after the screen has jerked up,  is on whatever was jerked up from below, so don't get a double-click.  The fourth line is annoying because it overwrites the directory information with information you don’t care about here.

So, is there a way to display the panel pane without any of these lines?

Thanks

BTW, how are you coming with the problem creating remote folders with Windows 7?

Steve

**Comment by morassman** [comment]
Hi Steve

Those lines are completely out of Atom Commander's scope. If you opened the search view and you don't want it to display anymore then you should close it.

As for the line at the bottom. From a previous issue you logged we determined that the buttons at the bottom of the panel are not showing on Windows, or at least Windows 7. The fact that the status bar at the bottom overlap may be a result of that as well. It may even be related to the jumping behaviour.

I've mentioned that I do not have Windows at home, but I do have access to it at work, even though it's someone else's PC. I've opted to rather install Windows on my MacBook, but it's currently at the iStore for repairs. Once I get it back and Windows installed on it I'll be able to look into the display and remote folder issues that seem to be only appearing on Windows. Until then it's unfortunately not that easy to debug, because I haven't seen any of this behaviour on my Mac.

**Comment by toonbon** [comment]
"If you opened the search view and you don't want it to display anymore then you should close it."
How do I close the search view?
![sv](https://cloud.githubusercontent.com/assets/4875886/18367783/9b993e76-75d1-11e6-8235-558dc953d145.jpg)

**Comment by morassman** [comment]
You close it with the esc key. The panel says so at the top when you open it.

![find view](https://cloud.githubusercontent.com/assets/13697130/18378314/88462122-766c-11e6-938a-bb06bbb9f941.png)

**Comment by toonbon** [comment]
Ah!  I missed it because it's only visible until something is entered to find.  When there's something in the find field the top line is overwritten by the number of times it was found or a note saying it wasn't found, as in my last image above where the top line says:  "No results found for 'billing_address'".  Once you've used Find you have to manually select the field and delete the contents to see the Esc message again.

Thanks.
