### ISSUE TITLE
Compare Function

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#40]
The Atom Commander Compare function would be much more helpful , to me anyway, if 
1. Scrolling moved the left and right panes together, so the files stayed lined up
2. There was something to click that scrolled both panes to the _next_ difference
3. The line numbers didn't go away when you clicked in a pane
4. You could do a Ctrl-C in one pane to capture a selection and then a Ctrl-V  in the other pane to insert it
5. After clicking to do a Compare, an F10 was done automatically to switch the display to the Diff tab contents

The best diff program I've come across  on Windows  is ExamDiff Pro. It does 1-3, which helps  to make it a dream to use.     4 is done there by  clicking an arrow icon to move a selection from one pane to the other.

Thanks,
Steve Adams

**Comment by morassman** [comment]
The line numbers disappear due to an API change in Atom since compare was added. One of the functions I used was removed and I wasn't able to find an equivalent since the change.

As for the other points. These are good suggestions, but Atom Commander is not meant to be a diff tool. The diff was a feature request by someone else and I reluctantly added it, because there are many other tools and packages that are dedicated to this. I'm willing to integrate with one if possible, but I have no intention at the moment to add any more functionality to it. If you would like to implement these suggestions yourself then you're welcome to do a pull request.

**Comment by morassman** [comment]
I read up on Atom's latest API and there is a, albeit rather different, way of handling the clicks and highlighting. I've tested it and using the new, proper API doesn't cause the line number to disappear when clicking on the pane. This fix will be part of the next version.

**Comment by toonbon** [comment]
Great!

**Comment by morassman** [comment]
Fixed in v0.8.4
