### ISSUE TITLE
Remote File Copy Doesn't Work

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#42]
A remote file copy, from one remote pane to the other, doesn't do anything.  Just an error message saying that the the copy isn't supported, if that's the case,  would be a help.

**Comment by morassman** [comment]
You already asked about it in [this](https://github.com/morassman/atom-commander/issues/37) issue.

"I notice a couple of other strange things, though. I'm not able to copy a remote folder or file from one remote to another."

You can read my reply there.

**Comment by toonbon** [comment]
You point out that FTP doesn't have an operation that moves data from one remote connection to another  so you would have to do it by downloading from one connection and then uploading to the other, and that would be slow.  But the alternative for us is to manually 1) do a Ctrl-A Ctrl-C on the source file, 2) create the target file on the second connection, , and 3) do a Ctrl-V on the target file. Doing all that manually is _much_ slower than Atom Commander running through the code to do it.   

Just a thought.

**Comment by morassman** [comment]
Hi Steve.

That's true, but it's not just the speed I am taking into consideration, but also the effort to implement something like that. The reason Atom Commander is embedded in Atom, a text editor, is so that one can open and edit files from it. Yes, there are some file system operations, such as copy, delete, etc. but the primary purpose is to be able to navigate a file system to find files and edit them. I know that there's the risk that one would expect Atom Commander to be as feature rich as something like Total Commander due to the similar appearance and behaviour, but unfortunately that is not the case. It's not suppose to be a full fledged file manager.

However, the message you see does say that it is not _yet_ supported. It's obviously something that I am aware of and I would like to add this at some point, but given the primary purpose of Atom Commander and the limited time I have to work on it, it's not that high on my priority list right now.

I can't guarantee that it'll be done soon, but there's a good chance it'll be done eventually. The notification in the corner is a reminder to myself that it's still outstanding.

**Comment by toonbon** [comment]
I understand.   One more thought: if you made a full-featured  Atom Commander Pro you could probably roll everyone to it for $30.  I'd certainly pay for it.

**Comment by morassman** [comment]
Thanks :)

I've personally benefited much from the open source community and this package is one of the ways that I participate, so it will always be free.

Thanks for your feedback and suggestions. It's valuable to know how people use it and what they need. Between work and everything else, though, I can't really guarantee certain features, but I'm always willing to at least look into things and perhaps meet somewhere in the middle.
