### ISSUE TITLE
Menu options missing/not working related to FTP

### ISSUE THREAD

**Issue by ruberyguy** [morassman/atom-commander#45]
The help seems to suggest that the view item has the refresh option when using ftp. This seems not to be present. Also checking the menu code the option does not seem to be present.

Also the cache menu item never displays a dialog.

**Comment by morassman** [comment]
Hi @ruberyguy 

I'm not 100%, but it sounds like you might be looking for these in Atom's own menus? Atom Commander has its own menu, which is shown by holding `Alt` while Atom Commander has focus.

The following screenshot shows the `Refresh` option:
![refresh](https://cloud.githubusercontent.com/assets/13697130/19416525/35c3d19e-9393-11e6-9027-cf5ef55cde6e.png)

And this one shows the dialog from which to choose a server's cache:
![dialog](https://cloud.githubusercontent.com/assets/13697130/19416529/4e75701c-9393-11e6-9588-5494db20597a.png)

This dialog will only have entries if servers have already been added. It will at least be empty otherwise, but it should always appear.

Does this help? If not then I'll need more details, because I haven't been able to reproduce the problem you are describing.

**Comment by ruberyguy** [comment]
Hi, I'm new to atom so I may be missing something important. Appologies in advance. What you describe or show me is now what I see. I'm using windows 10 whether that makes a difference I'm not sure.

I see no blue buttons as shown in your examples. The menu is when I right click over the atom area. A popup menu appears divided in to two halves. The bottom halve matches up with the listed menu options of atom-commander in the help so I assumed this was atom-commanders additional menu options. Here is an image of the menu I am referring to:
![image](https://cloud.githubusercontent.com/assets/22861372/19416966/d02bc6d4-9397-11e6-837d-ef4422a76862.png)

**Comment by ruberyguy** [comment]
Sorry the menu I was referring was the context menu. The quick menu that you showed me does have the options. Silly me.

**Comment by morassman** [comment]
No worries :) Glad you found it!

**Comment by ruberyguy** [comment]
Thanks, just one more point though. Shouldn't it be on the context menu.

**Comment by morassman** [comment]
Good point. I must have missed it when I defined the menu items. I'll add it before the next update.

**Comment by ruberyguy** [comment]
Great! Thanks. Also note then when I click on the cache from the context menu nothing seems to happen but works fine from the quick menu.

**Comment by morassman** [comment]
Thanks. I'll fix that as well.
