### ISSUE TITLE
Great + suggestion

### ISSUE THREAD

**Issue by jachymcz** [morassman/atom-commander#53]
Hi,
great plugin! Just one suggestion, it would be great if you could toggle the display so that it could also be placed on the side, just like the tree view. 
I currently have the two panes next to each other at the bottom, but the extra space vertically is more useful than horizontally, so if the two panes could be below each other on the side it would be even better.

**Comment by morassman** [comment]
Hi @jachymcz 

Thanks for the suggestion. I agree that vertical space is more useful than horizontal space. It's with this in mind that I made it easy to hide and show the panel with F10 so that one can focus on the editor and only show the panel when one needs to browse the file system.

Atom Commander is based on Total Commander which, along with all its clones, typically show the panels next to each other. It's reasonable to assume that this is what people expect when using a dual pane file manager. Atom Commander also isn't suppose to replace the tree view, but rather to supplement it. I understand your use case, but I'm afraid this kind of layout isn't very common and doesn't quite justify the effort it would take to implement it.
