### ISSUE TITLE
Swith automatically to the editor view after a compare is launched.

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#56]
After launching a compare, it would be helpful to switch automatically to editor view, where the Diff pane can be viewed, since that seems to always be the next step.

**Comment by morassman** [comment]
What do you mean with "switch automatically to editor view"? The editor view is always visible. Also, when a compare is done, a new tab is added to the editor view and that tab is automatically selected to show the diff.

Please give more detail on the behaviour that you are looking for.

**Comment by toonbon** [comment]
"The editor view is always visible. "_

Hmmm.  Not on my screen, but maybe I don't have things set up correctly. My screen shows either:

![ac_tree_view](https://cloud.githubusercontent.com/assets/4875886/21298710/3f5091d8-c549-11e6-93ed-919dc3737dda.jpg)

or:
![ac_editor_view](https://cloud.githubusercontent.com/assets/4875886/21298714/49ca38b2-c549-11e6-9573-b61c96622fd3.jpg)

I never see them both and I switch between the views with F10. 
Is there a better way to set up my screen?

**Comment by morassman** [comment]
We spoke about this in [previous](https://github.com/morassman/atom-commander/issues/36) issue. Look at the screen shots I added to that issue and the arrows on the screen shots that point to the separator. You're suppose to see Atom Commander at the bottom and the editor above it. If this is not the case then it means that Atom Commander's separator has been dragged all the way to the top. Drag it down so that there can be space for the editor.

**Comment by morassman** [comment]
Have you been able to get everything to display properly yet?

**Comment by toonbon** [comment]
No, I haven't had time  yet to go through what you wrote.  But I'll get to it.

**Comment by morassman** [comment]
Hi @toonbon 

Can I close this issue or are you still experiencing this problem?

**Comment by toonbon** [comment]
Yes, go ahead and close it.
