### ISSUE TITLE
Additional settings

### ISSUE THREAD

**Issue by svartkanin** [morassman/atom-commander#75]
Hi,
is there a possibility to move the browser the the right instead of the bottom, this would be much better for wide-screens since the coding is usually done vertically not horizontally?

Further, is there on option for displaying only one browser instead of two?

Thanks

**Comment by morassman** [comment]
I've considered adding the ability to move the panel to the sides of the screen before. It didn't feel quite right though due to how atom-commander uses more space horizontally. Allowing one to show only one of the browsers as you suggest would make it more suited though.

Some of the code assumes that there are always two browsers, so I'll just have to be careful that I don't break anything.

**Comment by svartkanin** [comment]
Maybe you wouldn't have to remove the second one, you could place them beneath one another instead of next to each other (just a suggestion). 
And maybe then provide an option to enable 1+ panels at the same time

**Comment by morassman** [comment]
This behaviour has been added to version 0.10.0. Atom Commander now makes use of the new docks that has been added to Atom 1.17. The dock can be dragged to the left or right in which case the two browsers will be shown on top of each other. Under the settings you can also choose to show only one browser at a time when docked on the left or right.
