### ISSUE TITLE
Tabs support

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#8]
It would be great if there was tabs so you don't have to navigate between folders each time you need particular folders. Also ability to reorder tabs.

**Comment by morassman** [comment]
This would be useful. When I look into this I'll probably do it in stages. The first stage will have the ability to add and remove tabs. The second will allow reordering them.

**Comment by admdh** [comment]
+1

**Comment by morassman** [comment]
v0.5.0 has been released with support for folder tabs. I ended up doing both stages. Tabs can be added with Ctrl-T or Cmd-T and removed with Ctrl-R or Cmd-R. Tabs are selected with Ctrl-Left\Right or Cmd-Left\Right. They can also be reordered by holding down Ctrl-Shift or Cmd-Shift and pressing left or right. 

The Ctrl left and right shortcuts may not work on OSX, because these are already used by the OS, so the Cmd key would have to be used instead.
