### ISSUE TITLE
Unable to edit FTP credentials once saved

### ISSUE THREAD

**Issue by kikoking** [morassman/atom-commander#85]
I'm not sure why, but after a couple upgrades I noticed I was unable to edit the ftp anymore. I just figured out that the issue is the atom-material-ui theme. If you use the default installed theme then you can edit the FTP credentials just fine. 

Adding this as a bug, and a bug fix all at once.

**Comment by morassman** [comment]
Hi @kikoking 

This is actually a bug in atom-material-ui and has already been reported [here](https://github.com/atom-material/atom-material-ui/issues/430). The problem comes in with the SelectListView modal. This modal is used by atom-commander and many other packages, but atom-material-ui doesn't render it properly.

I'm going to close this issue, since it isn't a bug on atom-commander's side. Maybe keep your eye on the one reported at atom-material-ui instead.

**Comment by kikoking** [comment]
Yes! I figured out that it was atom-material-ui just recently and that it was affecting other ftp packages as well, I'm assuming rather just the list thing you are mentioning. I should have posted sooner about that, forgive me. Thank you so much for looking into it, and providing the best ftp package for Atom still to date!!

**Comment by morassman** [comment]
I'm glad you reported it here though. Someone else may log the same issue, but without knowing that atom-material-ui is the problem. It would have taken me a while to get to the bottom of it, but thanks to you I it will spare me a lot of effort :)
