### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by admdh** [morassman/atom-commander#9]
it would be great if terminal could be opened in current folder.

**Comment by morassman** [comment]
I agree. I also want to add the ability to open a file with the system default instead of with Atom. When it comes to opening the terminal I've also thought that it might be useful to integrate with existing Atom terminal plugins. That way one can choose whether the OS's terminal should be used or a plugin instead.

**Comment by admdh** [comment]
:+1:

**Comment by morassman** [comment]
The option to open the terminal in the current folder has been added to v0.4.0 as well as opening the folder in the OS's file manager. There is also an option to open files with the OS default. A short-cut for this is to open the file with Ctrl-Enter.

**Comment by admdh** [comment]
:+1:
